import MarkdownIt from "markdown-it";

/**
 * The one place authored text becomes markup.
 *
 * `html: false` is the load-bearing option. Authored strings are untrusted, and
 * with raw HTML disabled markdown-it escapes every tag it did not itself
 * generate into entities, so a scenario can never introduce an element the
 * author did not name as markdown. `tools/smoke.ts` check `6f` asserts exactly
 * that, and it is why the rest of the UI can go on writing authored strings
 * through `textContent`. Change this option and that check is what fails.
 *
 * `linkify: false` is deliberate: a bare URL in prose stays text, so a link is
 * only ever something the author wrote as one. `breaks: true` keeps the line
 * breaks a `|` block scalar implies.
 */
const md = new MarkdownIt({ html: false, linkify: false, breaks: true, typographer: false });

/**
 * Only these schemes become anchors; anything else renders as literal text.
 *
 * markdown-it's default rejects `javascript:` and `vbscript:`, but the list is
 * worth stating here rather than inheriting: `data:` and `file:` are rejected
 * too. A link that survives this is still not opened on click — see
 * `link-guard.ts`, which shows the destination first.
 */
md.validateLink = (url: string): boolean => /^(https?:|mailto:)/i.test(url);

/**
 * Tag every anchor so `link-guard.ts` can recognise it, and carry the resolved
 * destination on the element. `data-url` is the same normalized value the
 * `href` holds, so the dialog quotes the URL that would actually open rather
 * than the one as written.
 */
md.renderer.rules.link_open = (tokens, index, options, _env, self) => {
  const token = tokens[index];
  token.attrSet("class", "md-link");
  token.attrSet("target", "_blank");
  token.attrSet("rel", "noopener noreferrer");
  token.attrSet("data-url", token.attrGet("href") ?? "");
  return self.renderToken(tokens, index, options);
};

/**
 * An image renders as its alt text.
 *
 * A link waits for a click; an image does not — the reader's browser would fetch
 * it the moment the entry paints, handing whoever authored the URL an IP and a
 * referrer. Markdown therefore cannot reach the network at all. Project images
 * are the `image` UI element, which resolves through the pack's own assets.
 */
md.renderer.rules.image = (tokens, index, options, env, self) =>
  md.utils.escapeHtml(self.renderInlineAsText(tokens[index].children ?? [], options, env));

/**
 * Whether authored text carries block structure.
 *
 * A one-line string is inline, so a prose line beginning `-` or `#` cannot
 * silently become a bullet or a heading. A string containing a newline is a
 * block, which is what an author gets by writing a `|` scalar — YAML's `|`
 * always yields a trailing newline, so the block scalar itself is the opt-in.
 */
export function isBlockText(text: string): boolean {
  return text.includes("\n");
}

/** `render()` repaints the whole transcript, so the same strings are parsed repeatedly. */
const rendered = new Map<string, string>();
const CACHE_LIMIT = 500;

function cached(key: string, render: () => string): string {
  const hit = rendered.get(key);
  if (hit !== undefined) return hit;
  const html = render();
  if (rendered.size >= CACHE_LIMIT) rendered.clear();
  rendered.set(key, html);
  return html;
}

/**
 * Render authored text as inline markdown — emphasis, code, links and soft
 * breaks, but no block constructs.
 *
 * The `innerHTML` here is the one exception to the UI's `textContent` rule, and
 * it is safe for the reason given at the top of this file: every tag in the
 * string was generated by `md`, which escapes anything authored.
 *
 * The `md-inline` class marks the element as a markdown host, which is what
 * `styles/07-markdown.css` scopes its element rules to — the app has its own
 * global `em` rule (the file-tree counter) that authored emphasis must not hit.
 */
export function renderInline(el: HTMLElement, text: string): void {
  el.classList.add("md-inline");
  el.innerHTML = cached(`inline\u0000${text}`, () => md.renderInline(text));
}

/**
 * Render authored text as full markdown — paragraphs, lists, headings, fenced
 * code.
 *
 * The container must not be a `<p>`: block markdown emits its own, and a `<p>`
 * inside a `<p>` is invalid HTML that the browser repairs by splitting the
 * outer one.
 */
export function renderBlocks(el: HTMLElement, text: string): void {
  el.classList.add("md-block");
  el.innerHTML = cached(`block\u0000${text}`, () => md.render(text));
}
